version: "3.7"

services:
  app:
    image: node:lts
    working_dir: "/app"
    command: sh -c "npm i && npm run serve"

    ports:
      - "3000:3000"

    environment:
      APP_ID: 12345
      WEBHOOK_SECRET: 123456789abcdefghijklmnop
      PRIVATE_KEY_PATH: /private-key.pem

    volumes:
      - ./backportbot:/app
      - ./private-key.pem:/private-key.pem:ro
